apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-instance-ks.yaml
  - infrastructure-ks.yaml
  - infrastructure/certmanager   
  # - infrastructure/headlamp     # enable when ready
