apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-instance-ks.yaml
  - flux-operator/kustomization.yaml
  - infrastructure-ks.yaml
  - infrastructure/certmanager
  - devns-ks.yaml
